config/routes.rb
Rails.application.routes.draw do
  root 'games#index'
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  after_initialize :init
  serialize :p1_hashed_display_grid, Hash
  serialize :p1_hashed_ocean_grid, Hash 
  serialize :p1_hashed_game_grid, Hash 
  serialize :p2_hashed_display_grid, Hash
  serialize :p2_hashed_ocean_grid, Hash 
  serialize :p2_hashed_game_grid, Hash 
  serialize :p1_dg_history, Hash
  serialize :p2_dg_history, Hash
  serialize :score, Hash

  serialize :p1_display_grid, Array
  serialize :p1_ocean_grid, Array
  serialize :p1_game_grid, Array
  serialize :p2_display_grid, Array
  serialize :p2_ocean_grid, Array
  serialize :p2_game_grid, Array
  serialize :p1_game_grid_vessels, Array
  serialize :p2_game_grid_vessels, Array 

  def init
    self.pA_name  ||= "Neil" 
    self.pB_name  ||=  "PC"
    self.current_player ||= set_initial_player
    #self.current_player ||= "play_PlayerA"
    self.state  ||= "new"
    self.deploy_count ||= 0
    self.direction ||= "H"
    self.x_pos ||= "B"   
    self.y_pos  ||= "2"
    @letters = Hash.new
    @numbers = Hash.new
    fill_letters 10
  end

  before_save() do
    unless new_record? 
      case self.state
        when "deploying"
          all_reqd_values?
          create_deploying_grids
          @p1_game_grid.replace_grid(self.p1_game_grid)
          deploy_vessel
          store_deployed_vessels
          if self.deploy_count == "5"#Before going to playing screen show the deployed fleet one more time
              self.state = "deployed"
          end
          self.p1_hashed_game_grid = @p1_game_grid.grid_container
          self.direction = "H"
          self.x_pos = "D"   
          self.y_pos = "2"
        when "deployed" #Before going to playing screen set up all the game playing grids
          puts "In deployed"
          create_deploying_grids
          
          @p1_game_grid.replace_grid(self.p1_game_grid)

          auto_deploy_nonHumanPlayer
          self.p2_game_grid = @p2_game_grid.grid
          
          create_playing_setup_grids
          @p1_ocean_grid.replace_grid @p1_game_grid.grid
          @p2_ocean_grid.replace_grid @p2_game_grid.grid

          self.p1_hashed_display_grid = @p1_display_grid.grid_container
          self.p1_display_grid = @p1_display_grid.grid
          self.p1_hashed_ocean_grid = @p1_ocean_grid.grid_container
          self.p1_ocean_grid = @p1_ocean_grid.grid

          self.p2_hashed_display_grid = @p2_display_grid.grid_container
          self.p2_display_grid = @p2_display_grid.grid
          self.p2_hashed_ocean_grid = @p2_ocean_grid.grid_container
          self.p2_ocean_grid = @p2_ocean_grid.grid    

          store_deployed_vessels
          store_deployed_dg_history
          self.state = "playing"

          case current_player 
            when "PlayerA" #Human player to play 1st
              self.sub_status = "play_PlayerA"
            when "PlayerB" #PC to play 1st
              swap_and_store_grids
              swap_and_store_deployed_vessels
              swap_and_store_dg_history
              create_playing_grids
              play = @p1_display_grid.get_play
              result = @p2_game_grid.hit(play)
              self.message = add_message(play, result)
              #update_grids_with_result
              @p1_display_grid.update_grid(play, result)
              puts_the_history              

              self.p1_hashed_display_grid = @p1_display_grid.grid_container
              self.p1_display_grid = @p1_display_grid.grid
              self.p1_dg_history = @p1_display_grid.history
              "After play"
              puts_the_history
              self.p1_hashed_ocean_grid = @p1_ocean_grid.grid_container

              @p2_ocean_grid.update_grid(play, result)
              self.p2_hashed_ocean_grid = @p2_ocean_grid.grid_container
              self.p2_ocean_grid = @p2_ocean_grid.grid
              self.p2_hashed_display_grid = @p2_display_grid.grid_container
              #store_deployed_vessels
              self.p1_game_grid_vessels = @p1_game_grid.vessels_array
              self.p2_game_grid_vessels = @p2_game_grid.vessels_array
              
              self.sub_status = "show_PlayerB"
          end
          self.direction = ""
          self.x_pos = ""   
          self.y_pos = ""

        when "playing"  #TODO "Playing"
        case self.sub_status 
            when "show_PlayerB"
              show   
              self.sub_status = "play_PlayerA"
            when "play_PlayerA"
              do_a_play 
              self.sub_status = "show_PlayerA"
            when "show_PlayerA"
              create_playing_grids
              swap_players
              swap_and_store_deployed_vessels
              swap_and_store_dg_history
              create_playing_grids
              play = @p1_display_grid.get_play
              result = @p2_game_grid.hit(play)
              puts "result = #{result}"
              self.message = add_message(play, result)
              update_score result
              #score["PlayerB"] += 1 if result == "S"
              @p1_display_grid.update_grid(play, result)
              puts_the_history
              self.p1_hashed_display_grid = @p1_display_grid.grid_container
              self.p1_display_grid = @p1_display_grid.grid
              self.p1_dg_history = @p1_display_grid.history
              self.p1_hashed_ocean_grid = @p1_ocean_grid.grid_container
              @p2_ocean_grid.update_grid(play, result)
              self.p2_hashed_ocean_grid = @p2_ocean_grid.grid_container
              self.p2_ocean_grid = @p2_ocean_grid.grid
              self.p2_hashed_display_grid = @p2_display_grid.grid_container
              self.p1_game_grid_vessels = @p1_game_grid.vessels_array
              self.p2_game_grid_vessels = @p2_game_grid.vessels_array
              self.sub_status = "show_PlayerB"
          end
      end 
      else #When its a new record set all blank grids
        create_deploying_grids
        set_deploying_grids
        self.score = {"PlayerA" => 0, "PlayerB" => 0}
        self.state = "deploying"
    end
  end
 
private
  def add_message(play, result)
     self.current_player == "PlayerA" ? name = self.pA_name : name = self.pB_name
     msg = self.message = "#{name}'s shot landed in grid reference #{play}."
     case result
     when "H"
      msg += "The result was a hit."
     when "S"
      msg += "The vessel was sunk."
     else
      msg += "The result was a miss."
     end
     return msg
  end
  def create_playing_grids
    @p1_display_grid = DisplayGrid.new(10)
    @p1_ocean_grid = OceanGrid.new(10)
    @p1_game_grid = GameGrid.new(10)
 
    @p2_display_grid = DisplayGrid.new(10)
    @p2_ocean_grid = OceanGrid.new(10)
    @p2_game_grid = GameGrid.new(10)

    redeploy_vessels
    redeploy_history

    @p1_display_grid.replace_grid(self.p1_display_grid)
    @p1_display_grid.history = self.p1_dg_history
    @p1_ocean_grid.replace_grid(self.p1_ocean_grid)
    @p1_game_grid.replace_grid(self.p1_game_grid)
    
    @p2_display_grid.replace_grid(self.p2_display_grid)
    @p2_display_grid.history = self.p2_dg_history
    @p2_ocean_grid.replace_grid(self.p2_ocean_grid)
    @p2_game_grid.replace_grid(self.p2_game_grid)
  end

  def swap_and_store_grids
    p1_dg = self.p1_display_grid
    p1_h_dg = self.p1_hashed_display_grid
    p1_og = self.p1_ocean_grid
    p1_h_og = self.p1_hashed_ocean_grid 
    p1_gg = self.p1_game_grid

    self.p1_display_grid = self.p2_display_grid
    self.p1_hashed_display_grid = self.p2_hashed_display_grid 
    self.p1_ocean_grid = self.p2_ocean_grid
    self.p1_hashed_ocean_grid = self.p2_hashed_ocean_grid 
    self.p1_game_grid = self.p2_game_grid

    self.p2_display_grid = p1_dg
    self.p2_hashed_display_grid = p1_h_dg 
    self.p2_ocean_grid = p1_og
    self.p2_hashed_ocean_grid = p1_h_og 
    self.p2_game_grid = p1_gg
  end

  def swap_and_store_deployed_vessels
    self.p1_game_grid_vessels = @p2_game_grid.vessels_array
    self.p2_game_grid_vessels = @p1_game_grid.vessels_array
  end

  def swap_and_store_dg_history
    puts "before swap_and_store_dg_history" 
    puts_the_history
    self.p1_dg_history = @p2_display_grid.history
    self.p2_dg_history = @p1_display_grid.history
    puts "after swap_and_store_dg_history" 
    puts_the_history
  end

  def redeploy_vessels
    self.p1_game_grid_vessels.each do |vs|
      v = Vessel.new(vs["type"],vs["direction"],vs["x"],vs["y"],vs["hits"],vs["sunk"]) 
      @p1_game_grid.add_vessel(v)
    end
    self.p2_game_grid_vessels.each do |vs|
      v = Vessel.new(vs["type"],vs["direction"],vs["x"],vs["y"],vs["hits"],vs["sunk"]) 
      @p2_game_grid.add_vessel(v)
    end
  end

  def redeploy_history
    puts "Redeploying history"
    @p1_display_grid.history = self.p1_dg_history
    @p2_display_grid.history = self.p2_dg_history
    puts_the_history
  end

  def do_a_play
    create_playing_grids
    case current_player
      when "PlayerA"
        #puts "In PlayerA"
        check_all_playing_values?
        play = self.x_pos + self.y_pos
        #puts "play = #{play}"
        if @p1_display_grid.is_valid_ref?(play) && @p1_display_grid.can_take_hit?(play)
            make_a_play(play)
          else
            errors.add(:base, "Please choose a valid Grid Position")
            throw :abort
        end
        self.sub_status = "show_PlayerA"
      when "PlayerB"
    end
      self.x_pos = ""   
      self.y_pos = ""
  end

  def make_a_play(play)
    result = @p2_game_grid.hit(play)
    puts "result = #{result}"
    self.message = add_message(play, result)
    #score["PlayerA"] += 1 if result == "S"
    update_score result
    update_grids_with_result play, result
  end

  def update_score(result)
    puts "update_score(result)"
    score[self.current_player] += 1 if result == "S"
    #self.state = "gameover" if score[current_player] == 5
    puts  "score[self.current_player] = #{score[self.current_player]} "
    if score[current_player].to_i == 5
      puts "In here"

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    @games = Game.all
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    @game.save
    redirect_to edit_game_path(@game) 
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      puts "In update"
      if @game.update(game_params)
        format.html { redirect_to edit_game_path(@game), notice: 'Game was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:pA_name, :pB_name, :visible_grid, :direction, :x_pos, :y_pos)
      #params.permit(:p1_name, :p2_name, :visible_grid, :direction, :x_pos, :y_pos)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_deployform.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this Vessel from being deployed:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :direction %>
    <%= form.select :direction, ['','H', 'V'] %>
  </div>

  <div class="field">
    <%= form.label :x_pos %>
    <%= form.select :x_pos, ['','A', 'B','C','D', 'E', 'F', 'G', 'H', 'I', 'J'] %>
  </div>

  <div class="field">
    <%= form.label :y_pos %>
    <%= form.select :y_pos,['','1', '2','3','4', '5', '6', '7', '8', '9', '10']  %>
  </div>

  <div class="actions">
    <%= form.submit yield(:button_text) %>
  </div>
<% end %>

app/views/games/_displaygrid.html.erb
  p1_hashed_display_grid
  <div class="grid-container">

    <% {"Zero" => 0,"One" => 1,"Two" => 2,"Three" => 3,"Four" => 4,"Five" => 5,"Six" => 6,"Seven" => 7,"Eight" => 8,"Nine" => 9,"Ten" => 10}.each do |x,y| %>
    
    	<div class="X-CORDS-ROW-<%= x %>"><%= y %></div> 
    
    <% end %>

	<% ["A","B","C","D","E","F","G","H","I","J"].each do |x| %>
    
     <div class="<%= x %>-Zero"><%= x %></div> 
	
	<% end %>


	<% @game.p1_hashed_display_grid.each do |x, y|  %>
    <% if y == "X" %>
        <div class="<%= x %>"><div style="color:rgb(0,0,0)"><%= y %></div></div>
    <% elsif y == "@"  %>
        <div class="<%= x %>"><b><div style="color:rgb(255,255,255)"><%= y %></b></div></div>     
    <% elsif  y == "H"  %>
        <div class="<%= x %>"><b><div style="color:rgb(255,0,0)"><%= y %></b></div></div> 
    <% else %>
        <div class="<%= x %>"><b><div style="color:rgb(125,237,26)"><%= y %></b></div></div>      
    <% end %>
	<%end %> 
  
  </div>

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pA_name %>
    <%= form.text_field :pA_name %>
  </div>

  <div class="field">
    <%= form.label :pB_name %>
    <%= form.text_field :pB_name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_form2.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pA_name %>
    <%= form.text_field :pA_name %>
  </div>

  <div class="field">
    <%= form.label :pB_name %>
    <%= form.text_field :pB_name %>
  </div>

  <div class="field">
    <%= form.label :visible_grid %>
    <%= form.text_area :visible_grid %>
  </div>

  <div class="field">
    <%= form.label :hashed_grid %>
    <%= form.text_area :hashed_grid %>
  </div>

  <div class="field">
    <%= form.label :direction %>
    <%= form.text_field :direction %>
  </div>

  <div class="field">
    <%= form.label :x_pos %>
    <%= form.text_field :x_pos %>
  </div>

  <div class="field">
    <%= form.label :y_pos %>
    <%= form.text_field :y_pos %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/games/_gamegrid.html.erb
  <%= @game.pA_name %>'s Fleet
  <div class="grid-container">

    <% {"Zero" => 0,"One" => 1,"Two" => 2,"Three" => 3,"Four" => 4,"Five" => 5,"Six" => 6,"Seven" => 7,"Eight" => 8,"Nine" => 9,"Ten" => 10}.each do |x,y| %>
    
    	<div class="X-CORDS-ROW-<%= x %>"><%= y %></div> 
    
    <% end %>

	<% ["A","B","C","D","E","F","G","H","I","J"].each do |x| %>
    
     <div class="<%= x %>-Zero"><%= x %></div> 
	
	<% end %>

	<% @game.p1_hashed_game_grid.each do |x, y|  %>
  	<% if y == "X" %>
  		  <div class="<%= x %>"><%= y %></div>  
      <% else %>
        <div class="<%= x %>"><b><div style="color:rgb(255,0,0)"><%= y %></b></div></div>  
	  <% end %>
	<%end %> 
  
  </div>

app/views/games/_goplayform.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this Vessel from being deployed:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <p>
  
  <%= form.hidden_field :direction, value: "H" %>

  <div class="actions">
    <%= form.submit yield(:button_text) %>
  </div>
<% end %>

app/views/games/_oceangrid.html.erb
 p1_hashed_ocean_grid
  <div class="grid-container">

    <% {"Zero" => 0,"One" => 1,"Two" => 2,"Three" => 3,"Four" => 4,"Five" => 5,"Six" => 6,"Seven" => 7,"Eight" => 8,"Nine" => 9,"Ten" => 10}.each do |x,y| %>
    
      <div class="X-CORDS-ROW-<%= x %>"><%= y %></div> 
    
    <% end %>

  <% ["A","B","C","D","E","F","G","H","I","J"].each do |x| %>
    
     <div class="<%= x %>-Zero"><%= x %></div> 
  
  <% end %>

  <% @game.p1_hashed_ocean_grid.each do |x, y|  %>
    <% if y == "X" %>
        <div class="<%= x %>"><div style="color:rgb(0,0,0)"><%= y %></div></div>
    <% elsif y == "@"  %>
        <div class="<%= x %>"><b><div style="color:rgb(255,255,255)"><%= y %></b></div></div>     
    <% elsif  y == "H"  %>
        <div class="<%= x %>"><b><div style="color:rgb(255,0,0)"><%= y %></b></div></div> 
    <% else %>
        <div class="<%= x %>"><b><div style="color:rgb(125,237,26)"><%= y %></b></div></div>      
    <% end %>
  <%end %> 
  
  </div>

app/views/games/_p2displaygrid.html.erb
  p2_hashed_display_grid
  <div class="grid-container">

    <% {"Zero" => 0,"One" => 1,"Two" => 2,"Three" => 3,"Four" => 4,"Five" => 5,"Six" => 6,"Seven" => 7,"Eight" => 8,"Nine" => 9,"Ten" => 10}.each do |x,y| %>
    
    	<div class="X-CORDS-ROW-<%= x %>"><%= y %></div> 
    
    <% end %>

	<% ["A","B","C","D","E","F","G","H","I","J"].each do |x| %>
    
     <div class="<%= x %>-Zero"><%= x %></div> 
	
	<% end %>


	<% @game.p2_hashed_display_grid.each do |x, y|  %>
    <% if y == "X" %>
        <div class="<%= x %>"><div style="color:rgb(0,0,0)"><%= y %></div></div>
    <% elsif y == "@"  %>
        <div class="<%= x %>"><b><div style="color:rgb(255,255,255)"><%= y %></b></div></div>     
    <% elsif  y == "H"  %>
        <div class="<%= x %>"><b><div style="color:rgb(255,0,0)"><%= y %></b></div></div> 
    <% else %>
        <div class="<%= x %>"><b><div style="color:rgb(125,237,26)"><%= y %></b></div></div>      
    <% end %>
	<%end %> 
  
  </div>

app/views/games/_p2oceangrid.html.erb
 p2_hashed_ocean_grid
  <div class="grid-container">

    <% {"Zero" => 0,"One" => 1,"Two" => 2,"Three" => 3,"Four" => 4,"Five" => 5,"Six" => 6,"Seven" => 7,"Eight" => 8,"Nine" => 9,"Ten" => 10}.each do |x,y| %>
    
      <div class="X-CORDS-ROW-<%= x %>"><%= y %></div> 
    
    <% end %>

  <% ["A","B","C","D","E","F","G","H","I","J"].each do |x| %>
    
     <div class="<%= x %>-Zero"><%= x %></div> 
  
  <% end %>

  <% @game.p2_hashed_ocean_grid.each do |x, y|  %>
    <% if y == "X" %>
        <div class="<%= x %>"><div style="color:rgb(0,0,0)"><%= y %></div></div>
    <% elsif y == "@"  %>
        <div class="<%= x %>"><b><div style="color:rgb(255,255,255)"><%= y %></b></div></div>     
    <% elsif  y == "H"  %>
        <div class="<%= x %>"><b><div style="color:rgb(255,0,0)"><%= y %></b></div></div> 
    <% else %>
        <div class="<%= x %>"><b><div style="color:rgb(125,237,26)"><%= y %></b></div></div>      
    <% end %>
  <%end %> 
  
  </div>

app/views/games/_playform.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>






  <div class="field">
    <%= form.label :x_pos %>
    <%= form.select :x_pos, ['','A', 'B','C','D', 'E', 'F', 'G', 'H', 'I', 'J'] %>
  </div>

  <div class="field">
    <%= form.label :y_pos %>
    <%= form.select :y_pos,['','1', '2','3','4', '5', '6', '7', '8', '9', '10']  %>
  </div>

  <div class="actions">
    <%= form.submit yield(:button_text) %>
  </div>
<% end %>

app/views/games/edit.html.erb
<% if @game.state == "deploying"%>
   <% provide(:button_text, 'Deploy Vessel') %>
<% elsif @game.state == "deployed"%>
  <% provide(:button_text, 'Play!') %>
<% else %>
  <% if @game.sub_status == "play_PlayerA"%>
    <% provide(:button_text, 'Fire!') %>
  <% else %>
    <% provide(:button_text, 'Continue...') %>
  <% end %> 
<% end %>

<h1>Battlehips are Go!</h1>

 <div class="field">
   <h2>Player A = <%= @game.pA_name %> | Player B = <%= @game.pB_name %> | Current Player = <%= @game.current_player %></h2>
 </div>

 <% @fleet = { "0" => "Aircraft Carrier", "1" => "Battleship" , "2" => "Cruiser", "3" => "Submarine", "4" => "Destroyer"} %>

<% if @game.state == "deploying"%>
   <h3>Deploy your <%= @fleet[@game.deploy_count]%></h3>
<% elsif @game.state == "deployed"%>
   <h3>Your Fleet is deployed. Press Play to continue.</h3>
<% else %>
  <% if @game.sub_status == "play_PlayerA"%>
    <h3>Take aim ..... and fire!</h3>
  <% elsif @game.sub_status == "show_PlayerA" %>
    <h3><%= @game.message %></h3>
  <% else %>
    <h3><%= @game.message %></h3>
  <% end %>
<% end %>
 
state = <%= @game.state %> | substate = <%= @game.sub_status %> | deploy_count = <%= @game.deploy_count %>


<% if @game.state == "deploying"%>

  <div class="playwrapper">
    <div class="playbox a">
      <%= render 'gamegrid', game: @game %>
    </div>
  </div>
  <%= render 'deployform', game: @game %>

<% elsif @game.state == "deployed"%>
<p>Scores: <%= @game.pA_name %> = <%= @game.score["PlayerA"].to_s %>: <%= @game.pB_name %> = <%= @game.score["PlayerB"].to_s %>
  <div class="playwrapper">
    <div class="playbox a">
      <%= render 'gamegrid', game: @game %>
    </div>
  </div>
  <%= render 'goplayform', game: @game %>

<% else %>
<p>Scores: <%= @game.pA_name %> = <%= @game.score["PlayerA"].to_s %>: <%= @game.pB_name %> = <%= @game.score["PlayerB"].to_s %>
          <% if @game.sub_status == "play_PlayerA"%>
          
            <div class="playwrapper">
              <div class="playbox a">
                <%= render 'displaygrid', game: @game %>
              </div>
              <div class="playbox b">
                <%= render 'oceangrid', game: @game %>
              </div>
      
            </div>
                <%= render 'playform', game: @game %>

          <% elsif @game.sub_status == "show_PlayerA"%>
          
            <div class="playwrapper">
              <div class="playbox a">
                <%= render 'displaygrid', game: @game %>
              </div>
              <div class="playbox b">
                <%= render 'oceangrid', game: @game %>
              </div>
     
            </div>
            <% unless @game.state == "gameover" %>
                <%= render 'goplayform', game: @game %>  
            <% end %>
          <% else %>

            <div class="playwrapper">
              <div class="playbox a">
                <%= render 'p2oceangrid', game: @game %>
              </div>
     
            </div>
              <% unless @game.state == "gameover" %>
                <%= render 'goplayform', game: @game %> 
            <% end %>            
          <% end %>
<% end %>
<p>
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Games</h1>

<table>
  <thead>
    <tr>
      <th>PA name</th>
      <th>PB name</th>
      <th style="text-align:left;">Last Saved</th>
      <th colspan="2" ></th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.pA_name %></td>
        <td><%= game.pB_name %></td>
        <td><%= game.updated_at %></td>
        <td><%= link_to 'Play', edit_game_path(game) %></td>
        <td><%= link_to 'Destroy', game, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Game', new_game_path %>

app/views/games/new.html.erb
<h1>New Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>
<h2>Hashed Grid</h2>

<% @game.hashed_grid.each do |g| %>
<%= g %><p>
<% end %>

<p>
  <strong>PA name:</strong>
  <%= @game.pA_name %>
</p>

<p>
  <strong>PB name:</strong>
  <%= @game.pB_name %>
</p>

<p>
  <strong>Visible grid:</strong>
  <%= @game.visible_grid %>
</p>

<p>
  <strong>Direction:</strong>
  <%= @game.direction %>
</p>

<p>
  <strong>X pos:</strong>
  <%= @game.x_pos %>
</p>

<p>
  <strong>Y pos:</strong>
  <%= @game.y_pos %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>